global:
  # Global configuration
  smtp_smarthost: '${SMTP_HOST:-localhost:587}'
  smtp_from: '${SMTP_FROM:-alerts@utmify.com}'
  smtp_auth_username: '${SMTP_USERNAME:-}'
  smtp_auth_password: '${SMTP_PASSWORD:-}'
  smtp_require_tls: true
  
  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL:-}'
  
  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
  
  # Resolve timeout
  resolve_timeout: 5m

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alerts
route:
  # Root route
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  
  # Child routes
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 15m
      routes:
        # Database critical alerts
        - match:
            category: database
          receiver: 'database-critical'
        # Security critical alerts
        - match:
            category: security
          receiver: 'security-critical'
        # Infrastructure critical alerts
        - match:
            category: infrastructure
          receiver: 'infrastructure-critical'
    
    # Warning alerts - less frequent notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 2h
    
    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      group_interval: 1h
      repeat_interval: 24h
    
    # Business metrics alerts
    - match:
        category: business
      receiver: 'business-alerts'
      group_wait: 1m
      group_interval: 30m
      repeat_interval: 4h
    
    # Application alerts
    - match:
        category: application
      receiver: 'application-alerts'
      group_wait: 30s
      group_interval: 15m
      repeat_interval: 1h
    
    # System alerts
    - match:
        category: system
      receiver: 'system-alerts'
      group_wait: 1m
      group_interval: 20m
      repeat_interval: 2h
    
    # Maintenance window - suppress all alerts
    - match:
        alertname: MaintenanceMode
      receiver: 'null'
    
    # Test alerts
    - match:
        alertname: TestAlert
      receiver: 'test-alerts'

# Inhibition rules - suppress alerts based on other alerts
inhibit_rules:
  # Suppress warning if critical alert is firing
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'instance']
  
  # Suppress info if warning alert is firing
  - source_match:
      severity: warning
    target_match:
      severity: info
    equal: ['alertname', 'instance']
  
  # Suppress instance alerts if service is down
  - source_match:
      alertname: ServiceDown
    target_match_re:
      alertname: '(HighCPU|HighMemory|DiskSpaceHigh)'
    equal: ['instance']
  
  # Suppress database connection alerts if database is down
  - source_match:
      alertname: PostgreSQLDown
    target_match_re:
      alertname: '(PostgreSQL.*|DatabaseConnection.*)'
    equal: ['instance']

# Receivers - notification destinations
receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: '${DEFAULT_EMAIL:-admin@utmify.com}'
        subject: '[Utmify] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ if .EndsAt }}Ended: {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
          
          Labels:
          {{ range .Labels.SortedPairs }}- {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Annotations:
          {{ range .Annotations.SortedPairs }}- {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
        html: |
          <h2>Utmify Alert Notification</h2>
          {{ range .Alerts }}
          <div style="border: 1px solid #ddd; padding: 10px; margin: 10px 0;">
            <h3 style="color: {{ if eq .Labels.severity "critical" }}#d32f2f{{ else if eq .Labels.severity "warning" }}#f57c00{{ else }}#1976d2{{ end }};">
              {{ .Annotations.summary }}
            </h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
            <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
            {{ if .EndsAt }}<p><strong>Ended:</strong> {{ .EndsAt.Format "2006-01-02 15:04:05" }}</p>{{ end }}
            
            <details>
              <summary>Labels</summary>
              <ul>
                {{ range .Labels.SortedPairs }}<li>{{ .Name }}: {{ .Value }}</li>{{ end }}
              </ul>
            </details>
            
            <details>
              <summary>Annotations</summary>
              <ul>
                {{ range .Annotations.SortedPairs }}<li>{{ .Name }}: {{ .Value }}</li>{{ end }}
              </ul>
            </details>
          </div>
          {{ end }}
  
  # Critical alerts receiver
  - name: 'critical-alerts'
    email_configs:
      - to: '${CRITICAL_EMAIL:-admin@utmify.com,ops@utmify.com}'
        subject: '[CRITICAL] Utmify Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Runbook: {{ .Annotations.runbook_url }}
          Dashboard: https://grafana.utmify.com/d/{{ .Labels.dashboard_id }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}
          *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
        color: 'danger'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        severity: 'critical'
  
  # Database critical alerts
  - name: 'database-critical'
    email_configs:
      - to: '${DBA_EMAIL:-dba@utmify.com,admin@utmify.com}'
        subject: '[DATABASE CRITICAL] {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database-alerts'
        title: '🗄️ Database Critical: {{ .GroupLabels.alertname }}'
        color: 'danger'
  
  # Security critical alerts
  - name: 'security-critical'
    email_configs:
      - to: '${SECURITY_EMAIL:-security@utmify.com,admin@utmify.com}'
        subject: '[SECURITY CRITICAL] {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🔒 Security Critical: {{ .GroupLabels.alertname }}'
        color: 'danger'
  
  # Infrastructure critical alerts
  - name: 'infrastructure-critical'
    email_configs:
      - to: '${INFRA_EMAIL:-infra@utmify.com,admin@utmify.com}'
        subject: '[INFRASTRUCTURE CRITICAL] {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#infrastructure-alerts'
        title: '🏗️ Infrastructure Critical: {{ .GroupLabels.alertname }}'
        color: 'danger'
  
  # Warning alerts receiver
  - name: 'warning-alerts'
    email_configs:
      - to: '${WARNING_EMAIL:-ops@utmify.com}'
        subject: '[WARNING] Utmify Alert: {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        color: 'warning'
  
  # Info alerts receiver
  - name: 'info-alerts'
    email_configs:
      - to: '${INFO_EMAIL:-monitoring@utmify.com}'
        subject: '[INFO] Utmify Daily Digest'
        body: |
          Daily monitoring digest for {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#monitoring-digest'
        title: 'ℹ️ Daily Digest: {{ .GroupLabels.alertname }}'
        color: 'good'
  
  # Business alerts receiver
  - name: 'business-alerts'
    email_configs:
      - to: '${BUSINESS_EMAIL:-business@utmify.com,product@utmify.com}'
        subject: '[BUSINESS] Utmify Metrics Alert: {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#business-metrics'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        color: '#ff9800'
  
  # Application alerts receiver
  - name: 'application-alerts'
    email_configs:
      - to: '${DEV_EMAIL:-dev@utmify.com}'
        subject: '[APPLICATION] {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#application-alerts'
        title: '🚀 Application Alert: {{ .GroupLabels.alertname }}'
        color: '#2196f3'
  
  # System alerts receiver
  - name: 'system-alerts'
    email_configs:
      - to: '${SYSTEM_EMAIL:-sysadmin@utmify.com}'
        subject: '[SYSTEM] {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#system-alerts'
        title: '🖥️ System Alert: {{ .GroupLabels.alertname }}'
        color: '#9c27b0'
  
  # Test alerts receiver
  - name: 'test-alerts'
    email_configs:
      - to: '${TEST_EMAIL:-test@utmify.com}'
        subject: '[TEST] {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#test-alerts'
        title: '🧪 Test Alert: {{ .GroupLabels.alertname }}'
        color: '#4caf50'
  
  # Null receiver - suppresses alerts
  - name: 'null'

# Time intervals for muting alerts
time_intervals:
  - name: 'business-hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '18:00'
        weekdays: ['monday:friday']
        location: 'America/Sao_Paulo'
  
  - name: 'weekends'
    time_intervals:
      - weekdays: ['saturday', 'sunday']
        location: 'America/Sao_Paulo'
  
  - name: 'maintenance-window'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['sunday']
        location: 'America/Sao_Paulo'

# Mute time intervals
mute_time_intervals:
  - name: 'maintenance'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['sunday']
        location: 'America/Sao_Paulo'